### ISSUE TITLE
Full info import.

### ISSUE THREAD

**Issue by tonymccallie** [cynicaloptimist/improved-initiative#1]
I understand and agree with why you only have the OGL creatures available publicly, but would there be any way to import the full list for personal use? Like these files available for d20 Flight apps?
https://github.com/ceryliae/DnDAppFiles

**Comment by cynicaloptimist** [comment]
Hey, sorry I didn't respond to you on this sooner.
https://github.com/cynicaloptimist/improved-initiative/blob/master/ts/LibraryImporter.ts contains an importer class for XML sourced from Fantasy Grounds resources. That class could be adapted to produce Improved Initiative friendly creatures from that project.

**Comment by tonymccallie** [comment]
Thanks!

**Comment by cynicaloptimist** [comment]
I added a feature to the dev branch that enables this. You can find it somewhat hidden in the Options tab, after the data import and export buttons. I'll probably be improving support for the feature by giving better control over handling duplicate creatures, but the functionality is there for you now. It should work with any of the Bestiary XML files from the DnDAppFiles project, but I've only tested it with the Monster Manual. I'd love your feedback.

You can demo the functionality at http://improved-initiative-dev.azurewebsites.net/
