### ISSUE TITLE
Allow Sorting/re-ordering of Encounter List

### ISSUE THREAD

**Issue by Xeteskian** [cynicaloptimist/improved-initiative#106]
It would be great if the list of encounters could be sorted or re-ordered.  Preparing for a published adventure means that I usually prepend each encounter with the area it can happen in, for example:
"B5 - The lost temple - treasure room"
"G7 - The Fox & Hound - tap room"

**Comment by cynicaloptimist** [comment]
Thanks @Xeteskian. I'm not sure that I'll specifically enable sorting and reordering, but I am planning to add folders that you can put encounters into- would this be useful to you?

**Comment by Xeteskian** [comment]
Yeah, that would also work.  Thanks for all the great work you're putting into this, much appreciated.
