### ISSUE TITLE
Multiple run initiaive stack user input actions

### ISSUE THREAD

**Issue by ostelaymetaule** [cynicaloptimist/improved-initiative#12]
If the button "Run Initiative" is pressed multiple times and the player initiative is not confirmed after the first time this will stack the "run initiative" procedure. 
Example: "Run initiative" is pressed. Input for a player character appears. "Run initiative" is pressed one more time. Now you need confirm the player initiative 2 times to be able to continue.

Proposal: 
- block the "run initiative" command untill all user inputs are complete.

or 
- do not stack initiative and only handle single input for initiative per player

**Comment by jimtahu** [comment]
This happens with damage, and it can be quite obnoxious, as I can get off track with what damage has already been applied.

**Comment by cynicaloptimist** [comment]
I'm hesitant to make any changes that would block commands when the app is waiting on user input. I could see an exception being made when rolling initiative. Right now, the only behavior that requires the `UserPollQueue` (aka stack of input dialogs) is the roll initiative feature- in other cases, it can function just fine as a single current `UserPoll`.

Here are a few options I see to improve the `UserPollQueue` behavior:

1. Display all queued dialogs, starting with the oldest. May cause a lot of visual noise and appearance of scroll bars when rolling initiative.
2. Display current dialog, and an indicator of how many other dialogs are pending.
3. Disable queueing functionality, and take all initiative rolls in one input dialog.

Thoughts?

**Comment by jimtahu** [comment]
To me, 2 or 3 sound best. Option 3 would add the benefit of entering players rolls "out of order".

**Comment by cynicaloptimist** [comment]
I've made an improvement here by preventing multiple initiative rounds from being queued, but I still may inline all of the PC rolls.

**Comment by captainfashion** [comment]
I believe by "inline" you mean to simply assign the values automatically, without confirmation. If so, then I'd advocate this approach. Adjust initiative values by exception, rather than by rule.

**Comment by cynicaloptimist** [comment]
The handling of user polls (now known in the codebase as Prompts ((duh)) ) has been updated. It will show all queued prompts at the same time, and block multiple initiative prompts from being launched.
See #71 and #69
