### ISSUE TITLE
Roll initiative box cannot be closed if players are in an encounter

### ISSUE THREAD

**Issue by FearTheViking** [cynicaloptimist/improved-initiative#120]
Whenever I start an encounter that my players are in, initiative rolls normally, but I'm unable to close the roll initiative box afterwards unless I remove the players from the encounter. The box closes normally when only monsters are in an encounter.

**Comment by cynicaloptimist** [comment]
Hi FearTheViking,

Can you provide the statblock JSON for your player characters that you're having this issue with?

Thanks!

**Comment by FearTheViking** [comment]
Sure, here they are:

`{
  "Id": "h4ybgdpk",
  "Name": "Gra'Shak (Pero)",
  "Source": "",
  "Type": "Human",
  "HP": {
    "Value": 99,
    "Notes": "11d8+44"
  },
  "AC": {
    "Value": "21",
    "Notes": ""
  },
  "InitiativeModifier": 0,
  "Speed": [
    "40 ft."
  ],
  "Abilities": {
    "Str": "21",
    "Dex": "20",
    "Con": "19",
    "Cha": "8",
    "Int": 10,
    "Wis": "16"
  },
  "DamageVulnerabilities": [],
  "DamageResistances": [],
  "DamageImmunities": [],
  "ConditionImmunities": [],
  "Saves": [
    {
      "Name": "Str",
      "Modifier": "9"
    },
    {
      "Name": "Dex",
      "Modifier": "9"
    }
  ],
  "Skills": [],
  "Senses": [],
  "Languages": [],
  "Challenge": "Monk 11",
  "Traits": [],
  "Actions": [],
  "Reactions": [],
  "LegendaryActions": [],
  "Description": "",
  "Player": "player"
}`

`{
  "Id": "gr617ugg",
  "Name": "Goor'Am (Marko)",
  "Source": "",
  "Type": "Fire Genasi",
  "HP": {
    "Value": 80,
    "Notes": "11d8+22"
  },
  "AC": {
    "Value": "16",
    "Notes": ""
  },
  "InitiativeModifier": 0,
  "Speed": [
    "30 ft."
  ],
  "Abilities": {
    "Str": "12",
    "Dex": "12",
    "Con": "14",
    "Cha": 10,
    "Int": "20",
    "Wis": "12"
  },
  "DamageVulnerabilities": [],
  "DamageResistances": [],
  "DamageImmunities": [],
  "ConditionImmunities": [],
  "Saves": [
    {
      "Name": "Int",
      "Modifier": "9"
    },
    {
      "Name": "Wis",
      "Modifier": "5"
    }
  ],
  "Skills": [],
  "Senses": [],
  "Languages": [],
  "Challenge": "Mystic 11",
  "Traits": [],
  "Actions": [],
  "Reactions": [],
  "LegendaryActions": [],
  "Description": "",
  "Player": "player"
}`

`{
  "Id": "n5kxkij3",
  "Name": "Dawnbringer Cacko (Stevo)",
  "Source": "",
  "Type": "Human",
  "HP": {
    "Value": 77,
    "Notes": "11d8+22"
  },
  "AC": {
    "Value": "17",
    "Notes": ""
  },
  "InitiativeModifier": 0,
  "Speed": [],
  "Abilities": {
    "Str": "14",
    "Dex": "11",
    "Con": "14",
    "Cha": "13",
    "Int": "11",
    "Wis": "20"
  },
  "DamageVulnerabilities": [],
  "DamageResistances": [],
  "DamageImmunities": [],
  "ConditionImmunities": [],
  "Saves": [
    {
      "Name": "Wis",
      "Modifier": "9"
    },
    {
      "Name": "Cha",
      "Modifier": "5"
    }
  ],
  "Skills": [],
  "Senses": [],
  "Languages": [],
  "Challenge": "Cleric 11",
  "Traits": [],
  "Actions": [],
  "Reactions": [],
  "LegendaryActions": [],
  "Description": "",
  "Player": "player"
}`

`{
  "Id": "0sf1rny7",
  "Name": "Azh'Dai (Neno)",
  "Source": "",
  "Type": "Dragonborn",
  "HP": {
    "Value": 68,
    "Notes": "11d6+33"
  },
  "AC": {
    "Value": "16",
    "Notes": ""
  },
  "InitiativeModifier": 0,
  "Speed": [],
  "Abilities": {
    "Str": 10,
    "Dex": "13",
    "Con": "16",
    "Cha": "18",
    "Int": "12",
    "Wis": 10
  },
  "DamageVulnerabilities": [],
  "DamageResistances": [],
  "DamageImmunities": [],
  "ConditionImmunities": [],
  "Saves": [
    {
      "Name": "Con",
      "Modifier": "7"
    },
    {
      "Name": "Cha",
      "Modifier": "8"
    }
  ],
  "Skills": [],
  "Senses": [],
  "Languages": [],
  "Challenge": "Sorcerer 11",
  "Traits": [],
  "Actions": [],
  "Reactions": [],
  "LegendaryActions": [],
  "Description": "",
  "Player": "player"
}`

**Comment by cynicaloptimist** [comment]
Looks like there's still a bug where everything breaks if you put non-numeric values into the Level field. Try removing the class name from each PC's level, that should help you out for now. I'll look into preventing this issue from happening in the future.

**Comment by FearTheViking** [comment]
Thanks! I actually just discovered the same thing through a process of elimination. :)
