### ISSUE TITLE
Auto roll initiative for creatures added to active encounter

### ISSUE THREAD

**Issue by azuretower** [cynicaloptimist/improved-initiative#127]
When a creature is added to an active encounter it would be nice if their initiative would be taken care of automatically.

**Comment by cynicaloptimist** [comment]
The app already does this as of 0.10.0, are you sure this is not happening?

**Comment by azuretower** [comment]
Dang, I hadn't tried it again since 0.10.0 I was just finally writing it down.  It does work just fine, I found a few other bugs though, I'll submit those.
