### ISSUE TITLE
Adding a creature while holding alt/option no longer works on Mac

### ISSUE THREAD

**Issue by azuretower** [cynicaloptimist/improved-initiative#128]
Adding a creature to the list as hidden by holding alt/option while clicking no longer works. This may be a Mac issue.

**Comment by lembata** [comment]
The issue is also present on windows

**Comment by azuretower** [comment]
This still doesn't work on Mac. And as much as I could test on my windows VM it doesn't work on windows either. Is this feature no longer supported?

**Comment by cynicaloptimist** [comment]
Oops, misread this as the multi-select bug. Will investigate, thanks.
