### ISSUE TITLE
Use a different URL for the player view so players can't trivially see DM view

### ISSUE THREAD

**Issue by Geeber** [cynicaloptimist/improved-initiative#149]
Maybe this is just me being paranoid, but unless I've missed something there's no authentication or password protection. So if one of my players checked out the site for about 30 seconds they would realize that they could just edit the Player URL by one character and see all the secrets. That's a big temptation for even the most fervently lawful good paladin to resist ;)

Lacking a more sophisticated authentication mechanism (like being able to set a password for the DM view - which would be awesome BTW), maybe there's a quick fix to just generate the player URL from the DM URL in an algorithmically reversible (but non-obvious-to-a-human) way? At least then my players would have to dig up the GitHub code to figure out the DM URL, which would probably be good enough. If you need ideas on such an algorithm, I'm happy to help (something like [ROT13](https://en.wikipedia.org/wiki/ROT13) - with an extension to handle digits - would probably be plenty good enough.)

Thanks for this tool - I haven't tried playing with it yet but it seems like it could be a huge help :)

**Comment by cynicaloptimist** [comment]
Hi Geeber,

Thanks for the issue. I'm aware of the vulnerability, but I figured the impact was pretty low so I honestly just didn't bother fixing it yet. The encounter details aren't actually accessible if the player visits /e/encounterId, but they would be able to 'pose' as the DM and send their own version of the encounter to attached player views. Again a weird edge case with minimal impact, IMHO.

I am planning to rewrite the player view component altogether after I ship Account Sync, but if you'd like to submit a PR to patch this in the meantime I'd be happy to review it.

Thanks!

**Comment by Geeber** [comment]
I see, I didn't realize that all of the "secret" state was stored client-side. That makes me less worried about it. Thanks!

I'd love to provide a patch but node/JS is not familiar territory for me, unfortunately. If I have a few spare minutes I might try to take a crack, but it's a long shot :)
