### ISSUE TITLE
Add SRD condition reference

### ISSUE THREAD

**Issue by devonjones** [cynicaloptimist/improved-initiative#16]
Conditions, with optional durations (so like blinded, 2 rounds). It would be great if it had the list of conditions, but even the ability to just add a condition to a combatant that could track how much time is left on it would be awesome. I would see these as like attached to the combatant, but the duration may be tied to the initiative of the combatant who added the effect (like the wizard casts a spell that causes fear, so the duration is tracked on his initiative, but it's attached to the enemies who are feared.

**Comment by devonjones** [comment]
It would be nice for this if it could display the condition text when the condition is clicked.
http://www.5esrd.com/gamemastering/conditions

Also, condition icons on the combatant would be nice.  Probably something could be found here: http://game-icons.net/

**Comment by captainfashion** [comment]
I find the notes/tags feature to handle this really nicely. It auto-completes the most common conditions, and I usually just add a comment on duration (1m = 1 minute, e3 = ends round 3, etc.)

**Comment by cynicaloptimist** [comment]
This is halfway done. I technically have the SRD text for the conditions, I'm just not settled on the best way to present it.
