### ISSUE TITLE
Form editor does not display correctly for some creatures

### ISSUE THREAD

**Issue by JukeBoxHeroTP** [cynicaloptimist/improved-initiative#161]
For example, it seems that the "Bandit" form editor is broken, both when editing library and single. What breaks it seems to be tied somehow to what parts are filled out, as I had the form editor for some PCs break upon trying to add something to them. I think it broke after saving, and it doesn't seem that it is consistent which stat makes it break. Removing what I added to the stat using the JSON editor allowed the form editor to work again.

**Comment by cynicaloptimist** [comment]
Hi @JukeBoxHeroTP, thanks for the bug- can you provide some more details on exactly which parts of the statblock form seem to reproduce the issue? Providing a screenshot of the error or display bug would also be helpful. Thanks!

**Comment by cynicaloptimist** [comment]
I've made some changes that might fix this bug- feel free to try the last version on the development branch deployment and let me know if it's still happening.

https://improved-initiative-dev.herokuapp.com/

**Comment by JukeBoxHeroTP** [comment]
When testing, it did not appear to be consistent as to which parts of the stat block caused it. For one player character I was able to add a speed with no issue, and for another it caused this bug. It does seem to be resolved in the development branch as far as I can tell. How quickly could I expect this fix to be in the live version?

**Comment by cynicaloptimist** [comment]
The fix is deployed now. Thanks!
