### ISSUE TITLE
Spell descriptions don't appear to have text wrapping

### ISSUE THREAD

**Issue by jdschabinger** [cynicaloptimist/improved-initiative#163]
Opening a spell makes a text box larger than the window can expand, and the view does not allow scrolling.  Browser zoom has to go to < 40%  (On my laptop screen/resolution) just to click the check box.

It appears that the spells should have text wrapping but it's not taking effect, expanding the spell to the longest paragraph's "width" on one line.

Chrome Browser at 100% zoom, 1366x768 resolution.
![image](https://user-images.githubusercontent.com/29957011/33518710-cb28122c-d767-11e7-9646-dc5cc662bfd6.png)

Chrome Browser at 33% zoom
![image](https://user-images.githubusercontent.com/29957011/33518771-f1585d98-d768-11e7-8d6e-6c9a4e3318b0.png)

**Comment by cynicaloptimist** [comment]
Thanks for the issue! I've deployed a quick fix for the CSS.
