### ISSUE TITLE
Can't remove the default players

### ISSUE THREAD

**Issue by Ddhuet** [cynicaloptimist/improved-initiative#176]
I can not remove Ellumyr, Gregorr, Shem, or Underfoot. 

This is quite distracting, as 50% of my Players list is just getting in the way.

**Comment by coffeeburrito** [comment]
@Ddhuet - I've found that refreshing the page after adding a custom character has the effect of hiding the four default characters you listed. I assume the code only adds them if none already exist.

**Comment by cynicaloptimist** [comment]
This is correct, but I'll leave the issue open because I need to improve the UX here to make it more obvious.

**Comment by WormSlayer** [comment]
I have added my own characters, then deleted the default ones, and refreshed the page many times, but Shem and co. remain on the list...

**Comment by cynicaloptimist** [comment]
This seems to be pretty annoying, I was chatting with another user today who would like to be able to hide all of the OGL content as well. I think a good approach here would be to add some items to the options tab to hide each of these pre built sets (sample players, OGL creatures, and OGL spells).

**Comment by captainfashion** [comment]
I have the same problem, though my characters existed long before the Default Characters were added.  

Still cannot delete these sample characters, which is annoying.
