### ISSUE TITLE
Add a log

### ISSUE THREAD

**Issue by devonjones** [cynicaloptimist/improved-initiative#19]
It would be super awesome if there was a log of what took place. Recording damage, addition and removal of notes, etc.

It would help to locate mistakes that were made in game (a player disputes something), as well as for people who like to write up notes/blog posts about what happened in a game session.

**Comment by cynicaloptimist** [comment]
The whole project is pending a rewrite using React + Redux, which will make this type of log very easy to implement, along with other quality of life features like an 'undo' button. This feature will be part of that effort.

**Comment by devonjones** [comment]
ok, I was looking at trying to pick up what's been done so far, is it not worth doing code right now as you do the React + Redux rewrite?

**Comment by cynicaloptimist** [comment]
I don't have a timeline for when I'll be able to do the, and I will port as much existing code as possible when I'm doing that. After the views are rewritten, I should be able to significantly simplify the encounter management code. Feel free to pick up the code now!
