### ISSUE TITLE
Don't show NaN/NaN in tracker when combatant has no HP value

### ISSUE THREAD

**Issue by chrisbloom7** [cynicaloptimist/improved-initiative#191]
Noticed last night when I setup som PC placeholders for a one-shot that if there is no value in their HP the tracker will display it as NaN/NaN. If the value is blank, should the tracker also show an empty space for that combatant?

**Comment by cynicaloptimist** [comment]
Interesting- I guess this only happens if you manually delete the default '1' in HP. This is a bug, the fix should be pretty straightforward in StatBlockEditor.ts#unMakeEditable() by providing a default value if parseInt fails. Default values should be 1HP, +0 initiative, 10 AC.
