### ISSUE TITLE
Questions about how different encounter URLs should work

### ISSUE THREAD

**Issue by chrisbloom7** [cynicaloptimist/improved-initiative#192]
This might actually be a broader question than just about the encounter URLs, but it basically boils down to this:

If I've a campaign setup at /e/abcd1234 (PCs created, bestiaries imported, creatures customized, encounters pre-generated and saved), my expectation was that if I went to the home page and generated a new II encounter at /e/efgh5678 that it would be a clean slate. That does not appear to be the case at the moment, and even if I disconnect my Patreon account the old data still persists. I'm guessing there is a copy stored locally for this to work. If I want a perfectly clean slate it appears that I have to use an incognito/private browsing session or use a different browser that I haven't used before. So I guess my question has a couple parts:

1. Is there an intended benefit to using a different URL once you've started customizing things on another?
2. Is there a non-destructive way to get a clean slate other than the way I described above, one that doesn't permanently remove data being used for other campaigns? (Covering both being logged in with Patreon with syncing setup, and not.)
3. Would it be beneficial to be able to track things at a campaign level and switch back and forth, perhaps as a pledge-level feature?
4. And a related question for my own sanity: Given the scenario that I described above - In main browser I am logged into my patreon account with sync enabled and main campaign details setup, and in an incognito browser session I started with a clean slate, not logged in, new campaign (one-shot) details setup - what would/should happen if in that incognito window I logged in with my Patreon account? Would the data be merged, or would one overwrite the other, or would there be a catastrophic collision with unpredictable results? (For the moment I've just exported a copy of the data, but curious to know if there's some expected behavior around that.)

**Comment by cynicaloptimist** [comment]
Good observations. The current encounter URL system grew organically, so it's a bit of a mess if you try to reason through it. Here's what's going on:
## Autosaved Encounters
- Every time you make a change in an encounter (add creature, next turn, apply damage, etc) the encounter is autosaved to localStorage at the current URL.
- If you load a URL that has an AutoSavedEncounter in localStorage, it will load that encounter.
- The main reason for this is to avoid refreshing the page being destructive, but it also allows you to bookmark your encounter view so you won't have to save it manually every time.
- There's no way to clear an autosaved encounter right now. IMHO, nobody's asked for it and nobody would use it.
## Collisions
- Every Encounter (and other entity) is marked with a ListingOrigin of `account`, `localStorage`, or `server`.
- They will never overwrite eachother, but the UI will prioritize them by hiding a `localStorage` entity if one of the same name exists from `account`.
## Multiple Campaigns
- This isn't planned just yet, but I can see it happening down the line. I'm starting to investigate what it would take to support Pathfinder statblocks, so this would be a useful feature for that.
- This could be supported by adding folders to the library.

Hope that helps- let me know if I missed anything!

**Comment by chrisbloom7** [comment]
Thanks for the response. I'm interested to know more about how each item's ListingOrigin is derived, i.e. why one over another. I'll try to track it down in the code as time allows, but if you have time to expand on that in the meantime I'd appreciate the added information. Otherwise I think you've addressed my questions.

> There's no way to clear an autosaved encounter right now. IMHO, nobody's asked for it and nobody would use it.

Consider me test case 1 ;) but I could see what it might not be used enough to justify making it a priority.

**Comment by cynicaloptimist** [comment]
ListingOrigin is set as follows:

- If the listing was preloaded as part of Improved Initiative, it's "server". This includes OGL content and sample characters
- If the listing was retreived from localStorage, it's "localStorage".
- If the listing was retreived from Account Sync, it's "account".

This is currently a client-only notion. If you have Account Sync, the app will still create localStorage listings but won't display them unless you're not logged in.

**Comment by chrisbloom7** [comment]
Thanks! Closing since it's currently working as you intended
