### ISSUE TITLE
allow AC reveal

### ISSUE THREAD

**Issue by devonjones** [cynicaloptimist/improved-initiative#20]
on a practical basis, many GMs, myself included will eventually tell the players the AC of monsters as their attacks narrow it down.  It would be useful if you could click on something to reveal the AC of monsters where they've narrowed it down so that they don't have to keep asking (telling one player doesn't necessarily mean they all hear it, and if it's on the board, I think they will quickly get used to looking there)

**Comment by chrisbloom7** [comment]
I've got a prototype of this at https://github.com/chrisbloom7/improved-initiative/pull/2. Looking for feedback on it before opening a PR against develop.
