### ISSUE TITLE
Improve Test Coverage

### ISSUE THREAD

**Issue by cynicaloptimist** [cynicaloptimist/improved-initiative#202]
I would love some help getting started on a test suite for Improved Initiative. I definitely should have started this on day 1, but I think it's time to swallow my pride and label this as _help wanted_.

End to end tests (ideally running in a headless browser like [Puppeteer](https://github.com/GoogleChrome/puppeteer) will be a great start to cover things like app load, library commands, encounter commands, and combatant commands.

**Comment by dprothero** [comment]
I'm happy to take a look at this if someone else hasn't started on it.

**Comment by cynicaloptimist** [comment]
@chrisbloom7 Is working in this right now, but I'm sure he'd love the help.
