### ISSUE TITLE
Legendary Actions

### ISSUE THREAD

**Issue by JukeBoxHeroTP** [cynicaloptimist/improved-initiative#203]
There should be a field for the number of legendary actions that a creature has. I think most(all?) have 3, but even so I think there should still be a field for if I want to make a creature with a different number.

**Comment by cynicaloptimist** [comment]
I don't see enough value in adding a dedicated field for this, since the app doesn't do any tracking of this and AFAIK it's never anything other than 3. As a workaround I think it would make sense to add Legendary Action Uses as a Speed or a Skill modifier.
