### ISSUE TITLE
Application Error when trying to log in with patreon

### ISSUE THREAD

**Issue by Tencer386** [cynicaloptimist/improved-initiative#204]
when attempting to log in using patreon it times out and says "Application Error" "An error occurred in the application and your page could not be served.

hope this helps and not to serious, I have come to rely on this to run my games and I have one tomorrow.

Thanks.

**Comment by cynicaloptimist** [comment]
Thanks for the report. Will fix ASAP, updates will be on Patreon: https://www.patreon.com/posts/17836225
