### ISSUE TITLE
spell links don't work with apostrophe 

### ISSUE THREAD

**Issue by azuretower** [cynicaloptimist/improved-initiative#210]
spells like "Maximilian's earthen grasp" that have an apostrophe do not correctly link to stat blocks.

**Comment by cynicaloptimist** [comment]
Are you sure about this? It seems to work fine in my cases. Is there possibly a mismatched UTF apostrophe in your case?

Thanks!

**Comment by cynicaloptimist** [comment]
@azuretower Closing for now, feel free to reopen with details.
