### ISSUE TITLE
New players get converted to new creatures

### ISSUE THREAD

**Issue by Keldon80** [cynicaloptimist/improved-initiative#211]
When i add a new player, and i save it, it get converted to a creature.
You can notice it becouse the form Level change to Challenge. 
And the combat tracker use it in the same way of monsters, roll hp etc...

**Comment by cynicaloptimist** [comment]
Hi Keldon, thanks for the report.

Can you share the exact steps that you take to reproduce this issue? What button are you clicking to add a new player?

Thanks!

**Comment by cynicaloptimist** [comment]
@Keldon80 Closing for now, feel free to reopen with repro steps.

**Comment by cynicaloptimist** [comment]
New details from [Clif Mobley](https://www.patreon.com/posts/18308803):

>One issue that seems to be cropping up for me as I learn the ropes (brand new user) is the fact that players I have made seem to be turning into monsters, this usually occurs after editing them for the second or third time. 
>
>I have looked through your github page and found one closed issue #211 of someone that appeared to have a similar problem. 
>
>I have tried recreating it but all I can tell is it changes the "level" option to "challenge" after editing something like HP. But when I look at the JSON for other players (that are working correctly) they also have the "challenge" description where "level" shows up.
>
>Sorry for the long winded description- I am not very tech savvy. Really all I need is help with how to turn them back from monsters to players. The only thing this really effects is the player view screen, as well as the encounter difficulty, it is counting my players as monsters (though thats not too far off for some of them)
'''

**Comment by cynicaloptimist** [comment]
A fix is deployed for this. If you have any PCs that got changed to NPCs and are stuck that way, try copying and pasting their JSON onto a freshly made PC and that should resolve the issue.
