### ISSUE TITLE
Add markdown support to traits and actions

### ISSUE THREAD

**Issue by devonjones** [cynicaloptimist/improved-initiative#22]
Add markdown support so we can make the traits and actions look like they are formatted in the book

**Comment by devonjones** [comment]
There's markdown in the ogl creatures I added, to make this look good, a patch would need to be in for the next release.

I'll see if I can bang one out.  I'm not super with javascript/node (I'm mostly a python/go dev), so we'll see how it goes adding a library

**Comment by cynicaloptimist** [comment]
Yeah, this is on the to do list before release. The best way to do this is with a Knockout custom binding handler, there's probably already a markdown one in npm we can take a dependency on. See CustomBindingHandlers.ts
