### ISSUE TITLE
Spells descriptions breaking

### ISSUE THREAD

**Issue by heyhler** [cynicaloptimist/improved-initiative#223]
Hi, first time ever posting to github, sorry if more details are needed.

When I'm reading a spell description in any view, any damage dice are returning up some syntax instead of the damage dice, usually ",[object Object],".  This doesn't happen for any other dice linking with any other type of entry.  Here's an example with Sacred Flame (happening with all sorts of spells though).

<img width="494" alt="screen shot 2018-05-04 at 1 32 50 pm" src="https://user-images.githubusercontent.com/34072119/39646204-409c7c40-4fa0-11e8-97e5-a998a98f7088.png">

I've tried importing spells from a DnDAppFile to fix this, but to no avail.  I'm using Safari 11.1 (13605.1.33.1.4), but able to reproduce this in Chrome 66.

**Comment by cynicaloptimist** [comment]
Definitely a bug, thanks for the report! Will fix ASAP.
