### ISSUE TITLE
Creature Folders do not persist across devices and different browsers

### ISSUE THREAD

**Issue by arcos** [cynicaloptimist/improved-initiative#226]
I added values to the folder fields of several creatures in the creatures list. The folder names are remembered, but the folders themselves do not appear when I load up my account on a different computer or a different browser on the same computer.

Computer 1:
![image](https://user-images.githubusercontent.com/143747/39662987-dc0babb8-5038-11e8-83d1-16ef9523a087.png)

Computer 2:
![image](https://user-images.githubusercontent.com/143747/39662981-c969b2f2-5038-11e8-91d7-43872ea963ee.png)

**Comment by cynicaloptimist** [comment]
Thanks for the detailed report. Working in this now.
