### ISSUE TITLE
Forward slash in imported creatures breaks URLs

### ISSUE THREAD

**Issue by ascendedguard** [cynicaloptimist/improved-initiative#234]
Steps to reproduce:

1. Import DnDFiles XML file for Monster Manual, which includes "Succubus/Incubus"
2. Attempt to add "Succubus/Incubus, or edit monster. Nothing happens.

Chrome console shows it's building a URL that includes the slash:

![image](https://user-images.githubusercontent.com/507305/40818911-9be74a7a-6527-11e8-9464-e8d99b11ab9a.png)

I do have Epic Initiative and Account Sync enabled, and there's no way to delete the entry currently because of the bad URL being generated.

**Comment by cynicaloptimist** [comment]
Thanks for the report. The DnDAppFiles importer isn't safely setting Ids on imported items, which should be an easy fix.

**Comment by cynicaloptimist** [comment]
Should be fixed now, give it another shot and let me know if you're stuck with a bad entry.

**Comment by ascendedguard** [comment]
@cynicaloptimist Did you already push the update out to http://www.improved-initiative.com ? If so, I'm still stuck with the bad entry with no way to use/remove it.

**Comment by ascendedguard** [comment]
@cynicaloptimist I tried uploading and creating a new version of it, but it appears to just result in 2 versions of the creature, and only the first one appears in the UI. 

Entity in question from `/my`:

    {"Name":"Succubus/Incubus","Id":"Succubus/Incubus","Path":"","SearchHint":"m fiend shapechanger monster manual neutral evil","Version":"1.5.6","Link":"/my/statblocks/Succubus/Incubus"}

Filtering it out server-side doesn't seem like a great solution, but I could see a filter [around here](https://github.com/cynicaloptimist/improved-initiative/blob/master/server/dbconnection.ts#L89) to work around it, otherwise you'd probably have to remove the bad entities from Mongo.

**Comment by cynicaloptimist** [comment]
Thanks very much for the additional details. I'll deploy a fix that should let you delete this entity using the UI, which will be safer than doing the DB work by hand. Sorry about the trouble in the meantime!

**Comment by cynicaloptimist** [comment]
You should be able to delete the offending entry in the UI now.
