### ISSUE TITLE
Markdown is not rendering in statblocks

### ISSUE THREAD

**Issue by cynicaloptimist** [cynicaloptimist/improved-initiative#236]

**Comment by ascendedguard** [comment]
Are you still wanting the statblocks to render markdown? I noticed you removed the rendering in ecee8b4c

To get it to render the markdown, you'd have to change the references to render the text to use dangerouslySetInnerHTML instead, from:

    const description = statBlock.Description && <div className="Description">{enricher.EnrichText(statBlock.Description)}</div>;

to:

    const descriptionHtml = {__html: enricher.EnrichText(statBlock.Description)}
    const description = statBlock.Description && <div className="Description" dangerouslySetInnerHTML={descriptionHtml}/>;

Although then it's going to render all HTML if other tags don't get sanitized in `EnrichText`

**Comment by cynicaloptimist** [comment]
Yeah, this one's a bit tricky since it needs to play nice with the other things that EnrichText does. Feel free to pick it up if you'd like!

**Comment by cynicaloptimist** [comment]
Fixed with b2b7530a2d4ebaeb0b1f4730215d8b1d141ae1e1
