### ISSUE TITLE
Encounter Sync failed - possibly due to unicode characters

### ISSUE THREAD

**Issue by DarkStar777** [cynicaloptimist/improved-initiative#256]
All it shows is "Error" -- everything else synced ok.

> Encounters: 23 local, 10 synced
> Backup and Sync local data
> 
> "error"

I have Unicode characters in my encounter notes which may be the cause.

In case you want to try some:

➊➋➌➍➎➏➐➑➒ ⛏ 💀   

![image](https://user-images.githubusercontent.com/8376117/42175823-75d07dba-7dec-11e8-99c8-92562f030dab.png)

**Comment by dprothero** [comment]
I could not reproduce this error. All my data synced just fine even with emoji characters like ➊➋➌➍➎➏➐➑➒ ⛏ 💀

**Comment by cynicaloptimist** [comment]
Thanks for trying to repro. This may have been "accidentally" fixed since the issue was filed. Will close for now.
