### ISSUE TITLE
Allow changing of HP (and other stats?) of added combatant.

### ISSUE THREAD

**Issue by RlndVt** [cynicaloptimist/improved-initiative#262]
After adding a combatant, you can click on it to view it's stats, but you cannot change these stats.

For example, if I want a zombie of a specific HP I either have to copy/edit the statblok, add the new zombie then delete the copy/undo the change. Or continually reload the  zombie while rolling for HP is on until I get lucky.

I notice that I can click on the 'hit die' next to the HP and get a pop-up showing the rolled HP, but applying (clicking on the check) that value doesn't change anything.

**Comment by cynicaloptimist** [comment]
This happens because if you've selected 'roll monster HP', it will completely ignore the contents of the HP Value box from the statblock. There's currently no way to set specific HP when you have enabled the random HP option, but it would make sense to fix this.

**Comment by RlndVt** [comment]
Correct me if I'm wrong, but you can't set a specific HP even if you haven't got the 'roll monster HP' set? 

Say you want a 'fat goblin', I would want to add a standard goblin (which gets the default 7HP), then change it's HP to 12.

**Comment by coreyjkelly** [comment]
Sounds like the same issue as #41 - Would need a unique state for the added combatant.

As a workaround, you can add Goblin, and grant it temporary hit points. Not ideal if you want healing to work. The other option is to enable the setting allowing negative hit points, and just keep the Combatant alive until it's taken the damage you want. 

Neither solution is great it you have enemy HP (or even colored state) visible to players.

**Comment by RlndVt** [comment]
For now I've been, as a workaround, created a new goblin with the HP I want, add it, then revert.

From that issue I gather that you would want to edit the `StatBlock` that gets copied with the `Combatant`.

Seems more complicating than I thought initially :)

**Comment by cynicaloptimist** [comment]
Yeah, this is a bug. A targeted fix would be to update [processStatBlock()](https://github.com/cynicaloptimist/improved-initiative/blob/df1274e085dc88b346c9b3795996ca04b5acfe79/client/Combatant/Combatant.ts#L94) to handle HP changes, but this needs to avoid breaking rolled HP. 

A better fix might involve:
* Remove MaxHP from Combatant, and change all references to its StatBlock's HP.Value
* When rolling monster HP, also update the Combatant's StatBlock HP with the rolled HP.

**Comment by autoferrit** [comment]
Was there ever a fix to this in the works? or an issue I can follow to track it since this one is closed?

**Comment by cynicaloptimist** [comment]
This was fixed; the Edit Combatant Statblock command should now work as expected. If you have some issue with it, please open a new issue with steps to reproduce.

**Comment by autoferrit** [comment]
I dont see a way to do this in the UI? I can click the HP and i can change the roll, but it doesnt effect the actual HP once i save it.
![image](https://user-images.githubusercontent.com/89895/57949224-ac255280-7898-11e9-87de-6dad66513ba5.png)

This doesnt work when clicking on the HP dice:
![image](https://user-images.githubusercontent.com/89895/57949307-e2fb6880-7898-11e9-9628-1fd0a90c34ef.png)

I did pull in the combatant from using kobold fight club. It did properly set the average HP. I just wanted to change it.

**Comment by cynicaloptimist** [comment]
The Edit Combatant Statblock command can be enabled from the Commands tab in the settings pane.
