### ISSUE TITLE
Succubus/Incubus Incorrect Action - 'Thunderous Stomp'

### ISSUE THREAD

**Issue by TheKrush** [cynicaloptimist/improved-initiative#276]
![image](https://user-images.githubusercontent.com/671500/44770472-0751c200-ab1d-11e8-9df2-45136318b54c.png)

Succubus/Incubus does not have the 'Thunderous Stomp' action by RAW. I think it was just a copy paste mistake.

**Comment by bemyak** [comment]
You can import files from https://github.com/storskegg/DnDAppFiles
This issue was fixes there: https://github.com/storskegg/DnDAppFiles/pull/10

**Comment by TheKrush** [comment]
Is it possible for things imported from DnDAppFiles to properly parse the 'source' out of the 'type' element so it goes properly into the source field? It'd also be great if size was converted back to the full word.

```
	<monster>
		<name>Air Elemental</name>
		<size>L</size>
		<type>elemental, monster manual</type>
```

these changes would make the imported data match the default data on improved-initiative match
