### ISSUE TITLE
On syncing: "error"

### ISSUE THREAD

**Issue by Wayneoween** [cynicaloptimist/improved-initiative#286]
Hi!

I just became a Patron and wanted to sync my local data. Worked for most of it, but for the encounters I got this error:

<img width="549" alt="screenshot 2018-09-29 11 29 16" src="https://user-images.githubusercontent.com/630640/46244136-0097c280-c3db-11e8-8da7-96cec47ce4d2.png">

The console (for the sake of other searching for text) said: `Failed to load resource: the server responded with a status of 413 (Payload Too Large)`.

<img width="862" alt="screenshot 2018-09-29 11 29 41" src="https://user-images.githubusercontent.com/630640/46244137-0392b300-c3db-11e8-8d40-aa5518e1b121.png">

I'm not sure how helpful this is for you. I am happy to give more information since its reproducible in Safari as well as Chrome for me.

**Comment by cynicaloptimist** [comment]
Hi Marius, sorry you're having this issue. Do you know if any of the
encounters that you're trying to sync are particularly large? The Network
tab might show some more information about the request.

--
Evan Bailey <http://www.linkedin.com/in/evangbailey>
Phone: (575) 694-2835

**Comment by Wayneoween** [comment]
I can't really say. I removed some encounters I already ran, which now fixed my issue.

None of the encounters had more than 14 combatants though.

I have 7 encounters synced now and I would think it's ok to close this issue until someone else (or me) runs into this issue again.

Thanks for all your work, this tool makes combat tracking for me so much faster and easier! 👍
