### ISSUE TITLE
Skills with spaces don't import correctly from D&DAppFiles

### ISSUE THREAD

**Issue by cynicaloptimist** [cynicaloptimist/improved-initiative#288]
From Keith Yates:

> the DnDAppFiles don't import correctly if the creature has any skill modifiers with a space in the name "Animal Handling" & "Sleight of Hand" they end up named only the first word and the modifier is null.

**Comment by blitzcodes** [comment]
@cynicaloptimist I've added a PR with test case included to help address this issue. Cheers, Homer
