### ISSUE TITLE
backgroundUrl isn't being properly set in the forms

### ISSUE THREAD

**Issue by TheKrush** [cynicaloptimist/improved-initiative#299]
If you load a json that has backgroundUrl set it doesn't appear in the form on the Epic Initiative page, and modifying that page when it's in this state seems to erase it's setting.

**Comment by TheKrush** [comment]
Refreshing the page after saving the backgroundUrl (which does correctly set it in the player view) makes it appear blank in the form upon visiting the Epic Initiative section again.

**Comment by cynicaloptimist** [comment]
Should be an easy fix in StylesChooser.tsx
