### ISSUE TITLE
SSL for www.improved-initiative.com

### ISSUE THREAD

**Issue by Wayneoween** [cynicaloptimist/improved-initiative#301]
Hi!

Depending on if you host it yourself I would suggest adding https://letsencrypt.org since every modern browser is showing some variation of "Not Secure" in front of the URL.

I could help with this!

Edit: Have not yet looked into it, but it _might_ need some sort of CORS Header since you are talking to Patreon for some data.

**Comment by cynicaloptimist** [comment]
Hi @Wayneoween, I agree this needs fixed- unfortunately it's blocked by #207 which I would like some help on if you have some ideas.

**Comment by cynicaloptimist** [comment]
Fixed this and #207. The app's canonical URL is now https://www.improved-initiative.com. Thanks for opening the issue @Wayneoween!

**Comment by Wayneoween** [comment]
Awesome! Thanks for the super fast reaction and your work! 💪
