### ISSUE TITLE
Additional Initiative Modifier options

### ISSUE THREAD

**Issue by captainfashion** [cynicaloptimist/improved-initiative#308]
In 5e, initiative is considered an ability check. There are conditions which can impose disadvantage on ability checks, such as Exhaustion. 

As such, would it be possible to add a feature to roll initiative at disadvantage for a PC/NPC?

**Comment by cynicaloptimist** [comment]
This would be good, as well as a "Flat" option to  just take flat `0 + InitiativeModifier`.

UI should change Roll with Advantage checkbox to a multibox with options. See StatBlockEditorFields.tsx
