### ISSUE TITLE
Saved encounters not showing creature numbers

### ISSUE THREAD

**Issue by Tencer386** [cynicaloptimist/improved-initiative#311]
Hi,

I was just making encounters for tomorrows game when I noticed that when loading a saved encounter it looses the creature numbering

for example before multiple veterans would look like

Veteran 1
Veteran 2
Veteran 3
ect

but now after loading an encounter its just

Veteran
Veteran
Veteran

Its only after saving the encounter then loading I have found, when adding them in the first place it seems to work fine.

Thanks!

**Comment by cynicaloptimist** [comment]
Fixed in 2.0.2
