### ISSUE TITLE
Left-side statblock different order than right-side statblock

### ISSUE THREAD

**Issue by TheKrush** [cynicaloptimist/improved-initiative#315]
![image](https://user-images.githubusercontent.com/671500/50111869-a3015e00-01f2-11e9-93f8-c413c3cd76f2.png)

**Comment by blitzcodes** [comment]
If I'm not mistaken, this was the intent, so that actions in combat are easily in focus for the active PC/NPC, while seeing the regular ordering on the right.

Perhaps though, this ordering could be a configurable option maybe.

**Comment by cynicaloptimist** [comment]
This is definitely by design.  Note the `displayMode` property on the component in `StatBlock.tsx`.
