### ISSUE TITLE
Ability to Create NPCs based on a Creature statblock.

### ISSUE THREAD

**Issue by TheKrush** [cynicaloptimist/improved-initiative#318]
It was mentioned the Character tab is eventually also going to support NPCs. It'd be good to allow the duplication of a character and/or creature and during the duplication (or maybe even just during any edit) the creature/character can be moved between the two tabs.

**Comment by realEBongo** [comment]
+1
Have you figured out any workaround besides manual entry for now?  I tried hacking my creature statblock JSONs to add the "player" tag.  That makes them persist across a "sweep", but it also prevents them from being included in an encounter, which is a bummer.  I tried exporting the whole JSON and hacking them to be "persistent players", but when I re-import they seem to be silently discarded.

**Comment by DarthGecko** [comment]
It looks like this issue has been fixed. Is it ready to be closed?

**Comment by cynicaloptimist** [comment]
Yep, thanks for the reminder
