### ISSUE TITLE
Can't import encounter from KFC when an autosave is present

### ISSUE THREAD

**Issue by colettak** [cynicaloptimist/improved-initiative#324]
When you try and start an encounter from KFC, it rarely works.  If any of the monsters are not part of the ORD, they don't show up.  If you had already started an encounter from KFC, nothing new will populate in Improved Initiative.

**Comment by cynicaloptimist** [comment]
Which specific monsters are you seeing issues with? The app should gracefully handle non-OGL creatures by just putting their name and HP into an empty statblock.

**Comment by colettak** [comment]
So after clearing all site data, I was able to get back to a fresh state.

The error still happens as follows:
Clear site data.
Go to KFC, add any monster (I used Devourers).  Select Party, then start combat in Improved Inititiative.
It works! I see the monsters with their AC, just like it always used to work.

However, now it is stuck in that state and won't change if I try and run another combat from KFC.

If I go back to KFC, select a different monster group, and try and Run in Improved Initiative again, the monsters don't update.  Even if I hit Clean Encounter, it just keeps the PC in the initiative order.  The new monsters selected don't show up.  
 
They are getting sent by KFC correctly I believe, as I see this in the html
`postedencounter="{"Combatants":[{"Name":"Intellect Devourer","HP":{"Value":21},"TotalInitiativeModifier":2,"AC":{"Value":12},"Player":"npc","Id":"mm.intellect-devourer"},{"Name":"Test","TotalInitiativeModifier":1,"HP":{"Value":150},"Player":"player"}]}"`

**Comment by cynicaloptimist** [comment]
Yeah, the other issue you're seeing is sort of by design, because the KFC import won't overwrite an existing combat. This can be changed.

**Comment by colettak** [comment]
Interesting.  That's the way I've always used it and never had a problem until the update.  However, even if I clear the existing combat it still won't work, as the PCs are saved in the combat area.

**Comment by cynicaloptimist** [comment]
This is a recent change, yes- I'll improve on this issue. In the meantime as a workaround, you'll need to manually delete all combatants in order to launch a new KFC encounter. Sorry about the inconvenience!
