### ISSUE TITLE
Allow enter to complete re-roll initiative

### ISSUE THREAD

**Issue by AJAnderson** [cynicaloptimist/improved-initiative#326]
When entering HP damage you can complete the form with the Enter key, but when you reroll initiative this isn't possible (default tabbed location?)

**Comment by AJAnderson** [comment]
Further, the difference is that I was modifying the HP, i.e. clicking on the pop up to give it focus. I was not doing this with reroll.

Perhaps this is a more general issue about where focus should go when a popup appears?

**Comment by cynicaloptimist** [comment]
I need to migrate the Roll Initiative prompt component to React in order to properly support this.

**Comment by AJAnderson** [comment]
Tested the new build, works great
