### ISSUE TITLE
Some creatures are not showing data in "Selected Combatant"  or active Combatant

### ISSUE THREAD

**Issue by eearmstro** [cynicaloptimist/improved-initiative#339]
Some of my creatures are no longer displaying their data in the selective or active combatant windows.
[sample.zip](https://github.com/cynicaloptimist/improved-initiative/files/2789305/sample.zip)

Some of my creatures display data just fine.  Don't see any obvious correlation between those that don't display.

**Comment by eearmstro** [comment]
Note that simply editing the creature and saving it will fix this issue.

**Comment by cynicaloptimist** [comment]
Can you share the statblock JSON of a creature that has this problem?

**Comment by joeboo1000** [comment]
> Can you share the statblock JSON of a creature that has this problem?

For further info I'm have this issue with the [Bheur_Hag](https://github.com/cynicaloptimist/improved-initiative/files/2813155/Bheur_Hag.txt) and [Night_Hag](https://github.com/cynicaloptimist/improved-initiative/files/2813156/Night_Hag.txt) but not the [Green_Hag](https://github.com/cynicaloptimist/improved-initiative/files/2813154/Green_Hag.txt)

And unfortunately editing the stat blocks does not fix this the issue for me.
