### ISSUE TITLE
Player screen splash should not have monster names 

### ISSUE THREAD

**Issue by FathomsDeep** [cynicaloptimist/improved-initiative#347]
Now that we can hide monster names, it defeats this purpose entirely if the name is displayed boldly under the splash image, 
![splashtag](https://user-images.githubusercontent.com/47292417/52174971-0e769f00-2751-11e9-918f-abb6e8985b68.jpg)

**Comment by cynicaloptimist** [comment]
This is not a bug, you just need to add more custom CSS. Try this:

.combatant-portrait__caption { display: none; }
