### ISSUE TITLE
Exporting drops a player

### ISSUE THREAD

**Issue by C-S-McFarland** [cynicaloptimist/improved-initiative#35]
When I add several players, then export them to a json, I see when I reload them (or look in the JSON file itself) that one player is missing. It doesn't seem to change depending on the number of characters you start with.

**Comment by cynicaloptimist** [comment]
I haven't been able to reproduce this issue. The exported JSON is just the contents of your browser's localstorage for the app, so it shouldn't be dropping anything. This might occur if there's a problem saving a player in the first place. Can you provide specific steps to reproduce the issue?

Thanks!

**Comment by C-S-McFarland** [comment]
Ok. I did this in an incognito tab in Chrome (54.0.2840.59).

1. Go to http://www.improved-initiative.com/
2. Click "Start an encounter"
3. Click "Save and close" on the dialog.
4. Add a player (I only edit the name and then I click the checkbox to accept it)
5. Click the gear and select Options and download the JSON file.
6. Save and Close
7. Click the gear, select options, and import an exported user data file. Import the file you just saved.
8. Add 5 more players (only edit name and accept for each)
9. Click the gear, select options, and download the JSON file.
10. Click save and close.
11. Click the gear, select options, and import an exported data file. Import the file you just saved.
12. Look at the player list.

I just went through those steps and it dropped the original player. 

I hope that helps.

**Comment by C-S-McFarland** [comment]
Also, when I look in the JSON file, I only see the players saved that do load next time. So it's during the export, I suspect, that the player is getting dropped.

**Comment by cynicaloptimist** [comment]
I followed these steps exactly, and I wasn't able to get a repro. Is it possible you weren't clicking the check mark on your last added player to save them? Doing this reproduces the issue for me.

Feel free to reopen with more details. Thanks!

**Comment by C-S-McFarland** [comment]
I am certain I am saving them. I do have new info that exclude the entire idea of saving a JSON export and importing it. Maybe this will help show the issue? https://youtu.be/GmTWwPA89DY

**Comment by cynicaloptimist** [comment]
This helps a lot- it looks like there may be something weird going on with the IDs of new player characters that are added. Thanks for going to the trouble here.

**Comment by C-S-McFarland** [comment]
I love this app quite a bit. So thanks for all your work. If I can help test or try anything to see if it's fixed, let me know.

**Comment by cynicaloptimist** [comment]
I just pushed a commit to the dev branch that I think solves this issue. Can you verify?

Try it on improved-initiative-dev.azurewebsites.net

**Comment by C-S-McFarland** [comment]
Looks good! I was able to test with reloads and exporting JSON. The JSON has all the characters over four. I tested to 7 players. Thank you!
