### ISSUE TITLE
Names of creatures no longer hidden

### ISSUE THREAD

**Issue by FathomsDeep** [cynicaloptimist/improved-initiative#352]
This is not a bug, you just need to add more custom CSS. Try this:

.combatant-portrait__caption { display: none; }

_Originally posted by @cynicaloptimist in https://github.com/cynicaloptimist/improved-initiative/issues/347#issuecomment-464291209_

Ran to implement this line in my CSS, and it did make the portrait captions disappear. thank you! But then I noticed that the names had *reappeared* in the list, alongside the little monster icon. I tried removing the CSS line I had just added, but the problem persisted. I rolled back to my previous build back-up... and still the names persist in list.

**Comment by cynicaloptimist** [comment]
Ok, can you share the entire contents of your Additional CSS field? And does this seem to be an issue with the whole custom CSS not saving?

**Comment by FathomsDeep** [comment]
Hmm. Well first, no, I'm afraid I can't give you my full CSS, because it's all disappeared again, and won't reload from my .json files, of which I have several backups. Tried rebuilding, but that too is failing to stick, reverting to blank/basic template on relog.  But no, the presence of the NPC names in the list didn't *seem* to be connected to that.  (I have made a note to myself to save my CSS edits in a seperate .txt file to avoid having to reconstruct it. The font injection trick isn't working anymore either.  Sorry- wish I could be more help. (My .json files are stuffed with custom creature imports, but I can upload those, if you feel they'll be any help.)

**Comment by FathomsDeep** [comment]
Slight update on all that- I hadn't realized, I'd been experimenting on the dev version, not the main page. Upon returning to the main, public page and uploading my .json backup, it loaded just fine. The names of creatures are *not* appearing in the list, only the icon, and the splashtags are appropriately hidden.  Saved that and exported, then re-imported on the dev version, to find that *some* of my customizations imported, but not all. Copied/pasted from the saved .CSS text file, resaved, and most custom edits appeared, and the splash tags were removed, but the names of the creatures was not hidden in the list. (It appears in addition to my monster icon.)  Here is the CSS in question:

@import url(//fonts.googleapis.com/css?family=Almendra);

.combatant.playercharacter  { fontface: 'Almendra', serif; }

.combatant.active { font-weight: bold; }

* { font-size: 16pt; }

    .combatant:not(.playercharacter) .combatant__name span { display:none; }

    .combatant:not(.playercharacter) .combatant__name::before { content: "🐉"; }

    #playerview .combatant.active .combatant__portrait img { 

        position: fixed;

        max-height:none;

        max-width:200px; 

        z-index:1;

        left: 0;

        top: 0;

    }

    .combatants, .combatant--header {

        margin-left: 200px;

    }

**Comment by cynicaloptimist** [comment]
Strange. I was able to get the custom CSS you provided to apply successfully:

![image](https://user-images.githubusercontent.com/3247737/53389072-a75c9c80-3942-11e9-90d3-22e0f196b535.png)

Not sure what's going on with it occasionally mis-applying the CSS. If you can narrow this down to a set of steps that consistently reproduces the bad behavior, that would be helpful.

**Comment by FathomsDeep** [comment]
I'm not great with code, as I said, I do wish I could be more specific or helpful. At this point, I opened the latest dev demo page, and it seemed to have remembered my previous code, so that's progress. I did nothing at all. Simply opened the options panel to see if the code was there, closed it again, launched the player view... and saw  [https://i.imgur.com/UECsRKR.jpg](url)

Everything is perfect, except the creature's name, hovering under or beside the creature icon.  I have not altered the code in any way from what I posted here last.

**Comment by cynicaloptimist** [comment]
Hey, I think I've figured this out, sorry it took a while for me to get a closer look at this. Try making this change, which should work in the current version of the app:
```
.combatant:not(.playercharacter) .combatant__name { font-size:0px; }

.combatant:not(.playercharacter) .combatant__name::before { 
    font-size: 20px; 
    content: "🐉"; 
}
```

**Comment by FathomsDeep** [comment]
Seems to work a treat, on both the public and dev versions of the page!  Looks like a bit of a work-around, but a perfectly functional one, so you'll have no complaints from me. :D  Thanks!

**Comment by cynicaloptimist** [comment]
Right on, thanks for the followup.
