### ISSUE TITLE
Players imported from DiceCloud treated as NPCs

### ISSUE THREAD

**Issue by CanaryGold** [cynicaloptimist/improved-initiative#356]
I've found that if the value for the "Player" attribute in the JSON is anything other that "player", the character is treated like an NPC.

Dicecloud however will load the value with the Dicecloud username, making all imported characters NPCs until you manually edit the value back to "player".

Is this a bug for Improved Initiative? Or for Dicecloud?

**Comment by cynicaloptimist** [comment]
This is technically a DiceCloud bug, but it would be reasonable for Improved Initiative to accept any non-empty string as an indicator that this is a player character. I'd accept a PR for this change.

**Comment by ThaumRystra** [comment]
This is a trivial fix on DiceCloud's side, I'll fix it there.
