### ISSUE TITLE
Saved encounters do not save characters, only creatures

### ISSUE THREAD

**Issue by jmswarts** [cynicaloptimist/improved-initiative#357]
I add PCs to the list of characters and then add them to encounters from there. When I save an encounter and return to it after refreshing the page, the creatures are the only things that populate in the encounter. All PCs are erased.

**Comment by cynicaloptimist** [comment]
This change is from 2.0. It's by design due to the new way that Characters work. I may make this configurable in the future.

See details at https://www.patreon.com/posts/23322208
