### ISSUE TITLE
Player Initiative Rolled With Wrong Modifiers

### ISSUE THREAD

**Issue by poltergeisha** [cynicaloptimist/improved-initiative#370]
For some reason, when my players' initiative is rolled, it rolls some of them with the wrong modifiers (different from what is in the stats I entered,) usually + or - 2, sometimes without or with advantage when there should or shouldn't be.

**Comment by cynicaloptimist** [comment]
Is this possibly because the initiative modifier stacks with dexterity bonus? If not, can you describe steps to consistently reproduce the issue? Thanks!

**Comment by poltergeisha** [comment]
Ah! That would explain the problem. i  have both init bonus and dex bonus for all my PCs.

**Comment by cynicaloptimist** [comment]
Makes sense, thanks for the confirmation!
