### ISSUE TITLE
Current Combatant Top of Statblock Appears At Bottom

### ISSUE THREAD

**Issue by poltergeisha** [cynicaloptimist/improved-initiative#371]
![image](https://user-images.githubusercontent.com/8014948/56260845-6e1cef00-609e-11e9-8572-8d64e149710e.png)

Here you can see I have the aboleth selected and also current combatant. Notice the placement of the top of the statblock.  Using the latest version of chrome.

**Comment by cynicaloptimist** [comment]
By design. The active creature shows traits and actions first.
