### ISSUE TITLE
Lair Actions

### ISSUE THREAD

**Issue by Wayneoween** [cynicaloptimist/improved-initiative#392]
Hi!

I was just designing an encounter within a lair and I was thinking, there could be an addable lair action row, of which you could decide the initiative order. But a minimal viable version would be somehow to add another special "Monster" that has initiative 20 but loses ties.

This does not need to contain the Lair Actions themselfs, but to remind the DM that they're there. I almost always forget them. A free text field with markdown support would probably be enough as you don't need them as often.

I can't say how thankful I am for all the work that went (and still goes) into making this! <3

**Comment by cynicaloptimist** [comment]
Thanks for the suggestion! I recommend using the Quick Add Combatant feature for this for now, but I have been thinking about adding something as a way to track abstract combatants (like lair actions, environmental hazards, traps, or even event sequences across a number of rounds). Stay tuned.

**Comment by Wayneoween** [comment]
Ah! Quick Add Combatant works for this fine as well! Thanks :)
