### ISSUE TITLE
Hidden monster-name icons should not have float-text.

### ISSUE THREAD

**Issue by FathomsDeep** [cynicaloptimist/improved-initiative#393]
The icons that replace monster names in the player view have hover-text telling the name of the monster, which sadly makes hiding the monster names irrelevant.

**Comment by cynicaloptimist** [comment]
Removed the float text.

**Comment by FathomsDeep** [comment]
Sorry it took me so long to test and respond- July's a busy month
 for me!  Brilliant, and thank you for looking into this for me. Tested on
the dev site, working perfectly. Still showing up in the public site
though. Not sure if you just haven't rolled it out in an update yet.  Hope
your month is as terrific, if less insane, than mine has been! :D

**Comment by cynicaloptimist** [comment]
Yep, this will come out with the next release. Actually a pretty insane month for me, v2.6 will be a smallish update when it releases. I'm troubleshooting an [issue with Patreon](https://www.patreondevelopers.com/t/api-returning-cloudflare-challenge/2025/4) now, once that's fixed I'll try to get the next version out the door.
