### ISSUE TITLE
Combatant Portrait Splash (can go offscreen)

### ISSUE THREAD

**Issue by TheKrush** [cynicaloptimist/improved-initiative#401]
Not sure if this is an actual issue or if we consider using CSS to fix it the solution but I'm going to submit this in case others find it and want to know how to get around it.

Current (caption on):
![image](https://user-images.githubusercontent.com/671500/60917660-4e810700-a246-11e9-873a-946a787379e5.png)

With CSS Changes (caption on):
```
.combatant-portrait { display: grid; height: 80%; }
.combatant-portrait__image { max-width: 80%; max-height: 80vh; margin: auto; }
```
![image](https://user-images.githubusercontent.com/671500/60920051-1da3d080-a24c-11e9-9112-98acd8df68c1.png)

With CSS Changes (caption off):
```
.combatant-portrait__caption { display: none; }
.combatant-portrait { display: grid; height: 100%; }
.combatant-portrait__image { max-width: 100%; max-height: 100vh; margin: auto; }
```
![image](https://user-images.githubusercontent.com/671500/60920320-c2261280-a24c-11e9-9725-b305cac3d21e.png)

**Comment by cynicaloptimist** [comment]
Feel free to submit a PR for this, thanks!
