### ISSUE TITLE
Creature statblock in existing encounter not updated when edits made

### ISSUE THREAD

**Issue by dprothero** [cynicaloptimist/improved-initiative#405]
If you:

1. Add a creature to an encounter
2. Edit that creature's statblock
3. Click the creature in the encounter, it's statblock does not contain any of the edits made in step 2.

Is this intentional, or something that would be good to fix?

**Comment by cynicaloptimist** [comment]
This is intentional. To edit the statblock of a creature in combat, you use the "Edit Combatant Statblock" command.

**Comment by dprothero** [comment]
Here's my situation, @cynicaloptimist, I have over a dozen encounters that include a specific monster (and multiple of those monsters). I wanted to add an image url to the monster, but it seems I need to go through every instance of every monster in all the encounters to add it. Or, I have to re-create the encounters.

**Comment by cynicaloptimist** [comment]
Ah, yes, unfortunately that scenario is a bit of a dead-end considering the way this functionality works. When you add a combatant from a StatBlock, it makes a copy of the StatBlock so it's no longer attached to the original Library source. I'm not sure how I'd want to change this behavior to better support what you're describing.
