### ISSUE TITLE
Character Sub-Folder Organization

### ISSUE THREAD

**Issue by rickymulder** [cynicaloptimist/improved-initiative#424]
Enhancement request:
I often create NPCs for different purposes within the characters section.  I currently find myself with 6 players and 12 NPCs.  It would be nice (and hopefully a simple cosmetic fix) to add single-depth subfolders within the Characters section, such that I could organize my "good" NPCs from my "bad" NPCs, and from my actual Players.  I would feel more comfortable importing my large library of NPCs from my written notes if I could choose a certain subset to scan through, rather than the whole 30+.

**Comment by cynicaloptimist** [comment]
You can do this today; use the Folder button in the StatBlock editor. There's an open issue to add a dedicated button for it: #272.
