### ISSUE TITLE
Items Being Deleted - Syncing Issue

### ISSUE THREAD

**Issue by gregorywalsh** [cynicaloptimist/improved-initiative#427]
When choosing the "Download all synced data to local data" option on a new browser (e.g. Safari on Mac) or browser session (e.g. in Chrome again) sometime some of the sync'd data is removed from the server, i.e. lost. Luckily I had some backups, so I was not affected.

I noticed this after following the guidelines to get around the storage limit issue, and also as a fresh start for use with version 2.8.

**Comment by cynicaloptimist** [comment]
2.8.2 may address this, let me know if it still repros.

**Comment by RedRing0fLife** [comment]
I am having a similar issue. Sometimes items of mine will be deleted after a sync, but the bigger problem for me sis that almost half of my statblocks won't sync at all, and my encounters refuse to sync. too.
![image](https://user-images.githubusercontent.com/56574032/66800008-7afd8c80-eee1-11e9-915b-65575c501af5.png)

**Comment by cynicaloptimist** [comment]
Should be fixed, please reopen this issue if it repros.
