### ISSUE TITLE
Improved Initiative missing monster stats when started from encounter builder

### ISSUE THREAD

**Issue by sbards** [cynicaloptimist/improved-initiative#436]
To reproduce: 
Start at https://kobold.club/fight/#/encounter-builder
Click the plus sign next to "Awakened Shrub" to add it to the encounter.
Click "Run in Improved Initiative"
Click on "Awakened Shrub" to see default stats

For comparison, you can add another shrub while in Improved Initiative to see the correct information.

**Comment by cynicaloptimist** [comment]
Thanks for the bug report, I think this has been broken for like 6 months and I never noticed. Should be fixed now!
