### ISSUE TITLE
Can't Sync Data To Cloud

### ISSUE THREAD

**Issue by RoaldRens** [cynicaloptimist/improved-initiative#441]
Hello there, I became a patron to sync my data between my devices and I managed to get my data to my laptop, but now I can't sink it back to the cloud. I tried deleting my data on the cloud but it still doesn't want to sync, any idea why this is happening?
![Screen Shot](https://user-images.githubusercontent.com/57014432/67594404-ef9bbb00-f76c-11e9-9da4-ba438abd6043.png)

**Comment by cynicaloptimist** [comment]
Can you share a copy of your exported user data JSON?

**Comment by RoaldRens** [comment]
Here you go, I hope it helps

[improved-initiative (10).zip](https://github.com/cynicaloptimist/improved-initiative/files/3774493/improved-initiative.10.zip)

**Comment by cynicaloptimist** [comment]
Thanks for submitting this issue. This should be fixed now, please reopen if you're still experiencing this issue.
