### ISSUE TITLE
Left/right pane beancounters out of sync

### ISSUE THREAD

**Issue by coreyjkelly** [cynicaloptimist/improved-initiative#455]
Beancounters seem generally broken in the left pane. Clicking on them sometimes shows changes in the right pane but not the left. Changing them in the right pane only shows the change there.

**Edit:** Initially thought this was specific to non-persistent combatants, but that doesn't seem to be the case. I've been poking around but haven't found a cause yet.

**Comment by coreyjkelly** [comment]
Haven't had time to look into this, and probably won't for a while. Ran a session extensively using Beancounters for tracking enemy spell slots, and just stuck to using the right panel. So this isn't completely experience-breaking. 

**Repro Instructions**
Chrome 79.0.3945.130 Official 64-bit on Windows 10

1. Add Ellumyr character to combat.
2. Give Ellumyr a counter: "[5/5]"
3. Add Gregorr to combat. 
4. Give Gregorr a counter: "[3/3]"
4. Begin Combat
5. Advance to second combatant.
6. Play with counters. Try changing the selected combatant, and the active combatant.

All counters work in both panes as expected while the first combatant is active, but start behaving strangely once the second becomes active. My intuition is that the generated counter components are somehow linked to each other (non-unique IDs, maybe?), so when one is clicked, the change is affecting another.

**Comment by SiR-DanieL** [comment]
+1 on this bug, I see it all the time. You can still use the panel on the left to mark spells, it just will not reflect as used as it would do when you use it on the right.

It is not breaking the system entirely but it would be nice to fix this.

**Comment by cynicaloptimist** [comment]
Yeah, this one's on my radar. I'm hoping to finish migrating the rest of the UI to React soon, which should help pin this down.

**Comment by cynicaloptimist** [comment]
I think this is fixed now.
