### ISSUE TITLE
Monsters are missing image source portrait data

### ISSUE THREAD

**Issue by Dan503** [cynicaloptimist/improved-initiative#474]
I'm surprised that none of the monsters in the data base have D&D image source data attached to them.

Is there any chance that monster image data can get saved into the data base?

**Comment by coreyjkelly** [comment]
The only creature/spell/other data that is included is what's covered under the OGL/SRD for D&D 5E. For creatures, this includes names, stats, abilities, etc, but not artwork. The art in the Monster Manual, or on D&D Beyond, for example, belongs to Wizards of the Coast.

Short of someone compiling a library of free-to-use art for the entire OGL, and hosting it somewhere relatively permanent, this wouldn't really be possible.

**Comment by cynicaloptimist** [comment]
Corey's comments are spot-on here. I wouldn't want to take a dependency on someone else's image URLs.
