### ISSUE TITLE
UI not adjusting for long list of combatants 

### ISSUE THREAD

**Issue by Nugler** [cynicaloptimist/improved-initiative#478]
When I have a long list of combatants, it will put the pop up windows that opens for initiative and spells at the very bottom, and sizes it to be as thin as possible. See screenshot.

Also, I can no longer select multiple combatants using ctrl.

![Annotation 2020-02-06 003446](https://user-images.githubusercontent.com/60727056/73908783-c49b2a00-4878-11ea-8de9-e2d17f16ffcd.png)

**Comment by Heruohta** [comment]
Same issues. The bottom window issue I've been able to manage around for a while but not being able to link multiple combatants with CTRL-Click is hurting.

**Comment by cynicaloptimist** [comment]
Both issues should be fixed now, thanks!
