### ISSUE TITLE
When "Allow Players to suggest tags" is enabled, header icons don't align properly.

### ISSUE THREAD

**Issue by truekaerf** [cynicaloptimist/improved-initiative#481]
When enabled, a new div, combatant__add-tag-button,  is added to the combatant li but no matching div is added to the combatant--header div.  This causes the heart icon to be off centered with the HP text.

Off:

![Improved Initiative - Tags Off](https://user-images.githubusercontent.com/38256419/74886852-46925500-5347-11ea-8f64-3abf8988cb2d.png)

On:

![Improved Initiative - Tags On](https://user-images.githubusercontent.com/38256419/74886854-472aeb80-5347-11ea-8614-9cb6decaad54.png)

**Comment by cynicaloptimist** [comment]
Got it, will be fixed in the next release. Thanks!
