### ISSUE TITLE
'keen-tracking' not found when 'npm start'

### ISSUE THREAD

**Issue by TheKrush** [cynicaloptimist/improved-initiative#486]
I'm getting this error, I installed 'keen-tracking' and it looks like it was missing from the package.json I'm going to put up a pull request to see what's different.

**Comment by cynicaloptimist** [comment]
Ensure all files in your branch are full up-to-date, keen-tracking was removed a long time ago.

**Comment by TheKrush** [comment]
Going to try deleting my node_modules folder, even resetting my fork to upstream/master is still getting the issue, and the main repo is getting a error about native-metrics not being compiled for windows and it doesn't seem to be able to find my visual studio installations

**Comment by TheKrush** [comment]
For reference, I forgot to run 'grunt' after updating.

**Comment by cynicaloptimist** [comment]
Yep, that makes sense. `grunt` does the full build, I recommend using that even if you're just doing UI development since it watches the code for changes, etc.
