### ISSUE TITLE
Dndbeyond importer does not correctly import some PC skills

### ISSUE THREAD

**Issue by bloodearnest** [cynicaloptimist/improved-initiative#492]
Skills that the player has expertise or 1/2 proficiency are not correctly imported into II. Also, Luck Stone's +1 to all skills is not included for non-proficient skills

Related to #491

**Comment by cynicaloptimist** [comment]
Deployed a fix for this today. BTW, the importer has its own repo here: https://github.com/cynicaloptimist/send-to-improved-initiative

**Comment by bloodearnest** [comment]
Thanks! I didn't realise it was open source
