### ISSUE TITLE
Not Importing Data From D&D Beyond 

### ISSUE THREAD

**Issue by Tucker2343** [cynicaloptimist/improved-initiative#494]
I noticed today when I went to import some characters to prepare for my next session there's a lot of information that isn't being pulled into improved initiative. I looked around but it doesn't appear anyone else is having this issue yet. 

Version: 0.3.1

Hoping someone can look at this soon, thank you in advance. :) 

![dnd import](https://user-images.githubusercontent.com/15664374/78852587-5d1d6a00-79e2-11ea-965d-e782917662f5.PNG)
![dnd import2](https://user-images.githubusercontent.com/15664374/78852589-5db60080-79e2-11ea-9eb4-d9dfe753d77b.PNG)
![import3](https://user-images.githubusercontent.com/15664374/78852591-5db60080-79e2-11ea-9fc2-a23643326853.PNG)
![import4](https://user-images.githubusercontent.com/15664374/78852593-5e4e9700-79e2-11ea-803e-1f8df47c47f3.PNG)

**Comment by cynicaloptimist** [comment]
Can you provide a public URL for the character sheet this is happening for?

**Comment by Tucker2343** [comment]
> Can you provide a public URL for the character sheet this is happening for?

Sure thing! Below are four character sheets I've attempted to import. 

https://www.dndbeyond.com/profile/Tucker2343/characters/21128561
https://www.dndbeyond.com/profile/One_Flame/characters/25889042
https://www.dndbeyond.com/profile/kisamefishfry/characters/25683883
https://www.dndbeyond.com/profile/Crusla/characters/25682890

**Comment by cynicaloptimist** [comment]
Seems to work ok for me:
![image](https://user-images.githubusercontent.com/3247737/78858616-d1a3d900-79e1-11ea-9456-9b3323804e1c.png)
What browser are you experiencing the issue with? Are there any other extensions you're running that might be interfering?

**Comment by Tucker2343** [comment]
I’m using google chrome, and I used it about week ago and I didn’t have any issues. I haven’t added any extensions since. Right now besides your extension I’m running Adblock plus.

**Comment by cynicaloptimist** [comment]
Strange. I'd say try disabling adblock, see if that makes a difference (I don't think that's the issue though). Also try removing and reinstalling the Importer extension.

**Comment by Tucker2343** [comment]
I will give that a try, if that doesn’t work I’ll let you know. Thanks for getting in touch with so quickly, I do appreciate that.

**Comment by Tucker2343** [comment]
Good Afternoon! 

So I'm still having this issue and I'm really not sure what's causing it. So far I've removed all extensions besides this one, that still having the same issue. I reinstalled the extension, still having the issue, then I cleared my cache "from the beginning of time" in chrome, still having the issue. Then I checked and saw that I didn't have the newest version of chrome so I did an updated. Then after doing that I was still having the issue, so then I uninstalled chrome, ran CCleaner to make sure chrome was 100% gone. Once was sure Chrome was gone then I did a reinstall and I'm STILL having the issue. So not sure what else I can do on my end to attempt to troubleshoot it.

**Comment by cynicaloptimist** [comment]
Hey, thanks for going to great lengths to try to narrow down this issue, I really appreciate it. Do you think you can produce a gif of you reproducing the issue so I can see if there's anything that stands out? I usually use [ScreenToGif](https://www.screentogif.com/) for this.

**Comment by Tucker2343** [comment]
Here you go! I hope this helps, let me know if you need anything else from me. 

![Combatissues](https://user-images.githubusercontent.com/15664374/79034161-9f2ce400-7b79-11ea-9571-0874bce86157.gif)

**Comment by cynicaloptimist** [comment]
That does help, although this is still really strange! It's interesting that it imports the languages, but nothing else, so the extension is at least partially working. I haven't heard from anybody else running into this issue. Have you configured any settings in D&D Beyond that might be affecting the way the character sheet is laid out? I know you can configure how Ability Scores are shown and the importer accounts for that, I wonder if there's anything else.

Another thing that might be helpful to look at is the Extension Details page for this extension, which you can view from your chrome://extensions/

**Comment by Tucker2343** [comment]
It's pull some information, but missing most of it. Here's a list of what it's grabbing. 
•	HP
•	Skills I have proficiency with
•	Movement Speed
•	Darkvison 60ft
•	Damage Resistances against poison
•	All of the languages my character knows

Here's a list of the things it's not grabbing
•	Character Name
•	Armor Class
•	Ability scores 
•	Saving Throws I have proficiency in
•	Character Icon 


I will be on my computer most of today, so I will keep on eye out for any replies from you and try to get back to as quick as I can. 

Thank you for looking into this issue for me, hoping we can find a resoltion soon, I do love using the tool that you made, it makes running combat so much easier. I love the import tool from D&D Beyond (when it's working lol) It makes it so much easier to import all my players data, makes it a lot easier on my end. :) 

Here's a screenshot of what version of Google Chrome I'm running
![image](https://user-images.githubusercontent.com/15664374/79045496-0d50c580-7bd1-11ea-8a57-4e328ae123cf.png)

Here's a screenshot of the extension details you asked for. 
![image](https://user-images.githubusercontent.com/15664374/79045345-37ee4e80-7bd0-11ea-8a9c-e5adbf39ea48.png)

**Comment by cynicaloptimist** [comment]
Can you try it in Firefox? That will help narrow down if it's some sort of
weird browser quirk.

**Comment by Tucker2343** [comment]
I just installed firefox, and I was able to get it to work just fine using firefox. So this must be an issue with just chrome.

**Comment by Tucker2343** [comment]
Update: So I ran the importer tool one time in firefox, and I went to use it again and now it's doing the exact  same thing as it is in google chrome.

**Comment by cynicaloptimist** [comment]
That's really interesting. I still haven't been able to reproduce the issue with any character sheets on my own machines. Here are a few options:

- If you've got access to another machine, see if the issue reproduces on other computers
- If you know how to use Chrome dev tools, you could try debugging the content script itself. It's not minified so you could stick a breakpoint here and troubleshoot:
![image](https://user-images.githubusercontent.com/3247737/79055514-96342500-7c02-11ea-90ff-8f7f8977b9f9.png)

If you're open to it, we could get on a call and screen share some time next week and we could investigate this together. I'm really curious as to what's going on with this bug.

**Comment by Tucker2343** [comment]
I do have another device I can try. If the same thing happens I would be open do doing a call and trying to dive into this. I’m really interested in what’s going on, and I’d like for it to start working again lol.

**Comment by Tucker2343** [comment]
Quick update, so I haven't tested it with another device yet, but I created a special monster and was able to import that and it pulled all the info without any issues. So it's just PC's that it's having issues importing.

**Comment by Tucker2343** [comment]
Since it keeps saying no monster portrait I decided to make a custom monster in D&D Beyond. Once I did I was able to import the monster without any issues at all! It's literally just PC's I can't import. 

Side note, I was able to do this in Google Chrome and Firefox. 



Google Chrome
![image](https://user-images.githubusercontent.com/15664374/79174833-86af0a80-7dc1-11ea-91de-1c4576fb6ace.png)
![image](https://user-images.githubusercontent.com/15664374/79174939-e2799380-7dc1-11ea-92a4-43f3e642d043.png)



FireFox
![image](https://user-images.githubusercontent.com/15664374/79174799-6bdc9600-7dc1-11ea-8fae-bacd761bce04.png)
![image](https://user-images.githubusercontent.com/15664374/79174943-e4dbed80-7dc1-11ea-9f79-c8c3dab52884.png)

**Comment by feadurbb** [comment]
I'm having a similar issue.
![firefox_2020-04-15_11-15-23](https://user-images.githubusercontent.com/48360982/79508288-40e38380-8007-11ea-9179-bd90eddd15e8.png)

**Comment by Tucker2343** [comment]
This is odd, I just went to test mine out for the hell of it, and it's working again?! 
![image](https://user-images.githubusercontent.com/15664374/79528533-d6930900-802f-11ea-97c4-e3282516294f.png)
![image](https://user-images.githubusercontent.com/15664374/79528548-e14d9e00-802f-11ea-9d48-d439ca309647.png)

**Comment by cynicaloptimist** [comment]
Thanks for the update. I'm wondering if the issue happens consistently if you run the extension very quickly after the page loads? i.e. does it work better if you wait a few seconds before activating the extension?

**Comment by Tucker2343** [comment]
If I click on the extension while it's still loading the page, it get this follow message I've attached a screenshot. But then after that if I wait a second and click on the extension once the character sheet loads and seems to still be working. So I don't know if you did anything, or if D&D beyond had an update that broke it for a short time but now its fixed? 

I'm going to be running two games of D&D this weekend, and in both games the characters are going to be leveling up, so I'm really hoping this will work on Saturday so I have a lot less work on my part lol. If I have any issues on Saturday I will let you know. 
![image](https://user-images.githubusercontent.com/15664374/79530992-9f742600-8036-11ea-9a94-2aeda6d8533d.png)

**Comment by feadurbb** [comment]
> 
> 
> Thanks for the update. I'm wondering if the issue happens consistently if you run the extension very quickly after the page loads? i.e. does it work better if you wait a few seconds before activating the extension?

Nope, still gives me null readings even if i leave it overnight before trying to use the extension.

**Comment by bloodearnest** [comment]
I've started seeing this recently, just for character imports, not for monsters.

So, I think I know what the issue is here: DDB's new character backend micro-service has been rolling out gradually over the last month (last week's dev update said ~90% of subscribers). This seems to have change some css classes (some things, but not all, that were prefixed ct-* are now prefixed ddbc-*), and maybe dom structure too. When I'm logged in, I see ddbc- classes. When I'm not, I see ct-* classes.

It hasn't touch the monster pages, hence why those still work.

I discovered this when my own WIP selenium based character scraper broke - such is the life of a scraping approach sadly :(

I wonder if it's worth developing a shared json file of CSS selectors, so that everyone scraping characters can collaborate and update it as the site changes.

There's still the issue that you need to fire the click events on various buttons in order to the underlying dom to actually render (thanks, react), e.g. PC spells.

Sigh. Oh for an api...

**Comment by chbigdome** [comment]
I have the same problem and found the change from ct to ddbc "prefixes" too.

on the left side is the character with the logged in account --> ddbc (not working)
on the right side is the character with the logged out account (incognito mode) --> ct (working)
![image](https://user-images.githubusercontent.com/47739127/79979054-33177d80-84a1-11ea-8c1c-b4008a5f253b.png)

**Comment by cynicaloptimist** [comment]
Ah, that would definitely explain it! It should be easy enough to update the CSS selectors I'm using to work with either prefix. Can somebody who is being served the new format share a the full html of a character sheet page for me to work with? Thanks!

**Comment by bloodearnest** [comment]
Here's one, copied from chrome dev tools.
[heston.html.gz](https://github.com/cynicaloptimist/improved-initiative/files/4517654/heston.html.gz)

**Comment by cynicaloptimist** [comment]
Ok, I've deployed version 0.3.2 for Chrome and Firefox which I think will fix this issue. Let me know if you still have trouble after the update and I'll take another run at it.

**Comment by chbigdome** [comment]
> Ok, I've deployed version 0.3.2 for Chrome and Firefox which I think will fix this issue. Let me know if you still have trouble after the update and I'll take another run at it.

On my side it works great now, thank you

**Comment by bloodearnest** [comment]
Works for me too, thanks!
