### ISSUE TITLE
Safari exports as UTF8 under some circumstances?

### ISSUE THREAD

**Issue by cynicaloptimist** [cynicaloptimist/improved-initiative#50]

**Comment by chrisbloom7** [comment]
@cynicaloptimist do you have any other debugging info you can provide for this? Can you please let me know what the expected behavior should be?

**Comment by cynicaloptimist** [comment]
I haven't got much, just had one user send me an exported JSON file when they were having trouble importing it. I can't find that file now, and I haven't heard anyone else hit the issue since, so I think we can close it.
