### ISSUE TITLE
Initiative mod not imported for character or monster

### ISSUE THREAD

**Issue by ZachHunt359** [cynicaloptimist/improved-initiative#501]
When importing a character sheet or monster using the extension, the initiative modifier does not seem to be captured. I'm using Chrome. When I looked at the JSON, there was no mention of initiative itself.

![Initiative not imported](https://user-images.githubusercontent.com/56412983/82613031-3756b980-9b79-11ea-9d3a-788ef61e1279.gif)
I'm not sure if this is related to the issue #494, or a separate problem.

**Comment by cynicaloptimist** [comment]
Fixed in latest version of the browser extension
