### ISSUE TITLE
Editing spells brake everything

### ISSUE THREAD

**Issue by Kiberia** [cynicaloptimist/improved-initiative#504]
Firstly, thanks for an awesome tool.

Error:
When I try to edit any spell, everything goes blank except background.

Console has errors
```
ImprovedInitiative.2.15.1.js:2 TypeError: Cannot read property 'Classes' of undefined
    at t.SpellEditor (ImprovedInitiative.2.15.1.js:2)
    <other minified calls>
```
and then
```
Couldn't load item keyed '<spell name you try to open> ' from async localForage store:
TypeError: Cannot read property 'Classes' of undefined
```

How to repeat:
Open Spells tab in library and try to edit any spell.

Browser: Chrome 83, repeatable in Incognito

P.S. Spell cards are shown as usual.

**Comment by cynicaloptimist** [comment]
Fixed, thanks for the report!
