### ISSUE TITLE
[Chrome] Huge input lag at every textbox.

### ISSUE THREAD

**Issue by Kiberia** [cynicaloptimist/improved-initiative#507]
I don't know if it just my PC, but after update 2.15 there seems to be huge input lag in Chrome.

I tried this on 2 pc's (both main mode with imported DnDAppFiles, and Incognito mode without ones) and when I type fast there's sometimes seconds (!) before any input shows in the textbox.

The problem is not existing in Firefox however.

Wonder if anyone have the same problem or am I just that unlucky.

OS: Windows 10 x64
Browser: Chrome 83.0.4103.61 fails
Firefox: 76.0.1 works fine

How to reproduce: Open textbox, e.g. "Change alias" and start spamming.

I can submit video if necessary.

**Comment by cynicaloptimist** [comment]
There were some text boxes in the StatBlock editor that had this problem, which should be fixed now. Where else are you seeing the issue? Thanks!

**Comment by Kiberia** [comment]
I still have lags in Character/Creature sheets stats block, "Change Alias" (f2), Update Persistent Notes, Add Tag, any Filter input.

**Comment by cynicaloptimist** [comment]
Thanks very much for the details. Latest update should correct most of these issues.
