### ISSUE TITLE
Don't depend on file locations during the concat build step

### ISSUE THREAD

**Issue by cynicaloptimist** [cynicaloptimist/improved-initiative#51]
I should be using some sort of `require` syntax to pull in dependencies instead of the simple concat logic. The build recently broke because a newer version of socket.io moved all their libraries into ./dist/

**Comment by Azzurite** [comment]
You're looking for http://browserify.org/. It scans a given .js file for `require(..)`-calls and bundles the file and everything that was `require(..)`'d up in a single file.
