### ISSUE TITLE
window resizing causes column spacing issue

### ISSUE THREAD

**Issue by rbmke** [cynicaloptimist/improved-initiative#520]
Love this tool, and am excited to use it in an upcoming game! However, when resizing the Player View window, the text for initiative numbers enlarges and intrudes on the Combatant column. Any idea how to fix this?

![image](https://user-images.githubusercontent.com/38476687/95813242-71ba2200-0ce5-11eb-8269-aa68e9595b18.png)

**Comment by CooperN** [comment]
+1 
![image](https://user-images.githubusercontent.com/18538580/97816182-23030680-1c59-11eb-825e-48163f110f6e.png)

**Comment by rbmke** [comment]
@CooperN , i ended up doing a temporary work around by using the inspector and changing the size of text for the initiative column (from 1.5em to 1em), and also changing the spacing between each columns to spread things out a bit. 

not a permanent solution but good for a quick fix!
