### ISSUE TITLE
"Automatically add creatures to initiative group" doesn't work right with manually entered initiative.

### ISSUE THREAD

**Issue by TKramez** [cynicaloptimist/improved-initiative#525]
I put a manually rolled initiative value into a group of monsters when starting an encounter. It did not use that value for those monsters though. I'm guessing that it's using the value from one of the other monsters in the group for initiative. I plan on looking into this once I get my fork downloaded and running.

**Comment by cynicaloptimist** [comment]
Fixed, thanks for opening the issue!
