### ISSUE TITLE
Honor line breaks in stat blocks

### ISSUE THREAD

**Issue by cynicaloptimist** [cynicaloptimist/improved-initiative#54]
from https://www.reddit.com/r/improvedinitiative/comments/5ivzsd/how_to_insert_carriage_returns_within_attribute/

**Comment by Azzurite** [comment]
You have to specify "line breaks". Line breaks are implicitly honored by markdown and you can't turn it off.

What is not honored are markdown block elements, like paragraphs, which is meant in this issue.

Right now, `renderInline` is being used for the markdown rendering in all of the stat block texts.

This means that paragraphs (signified by a "double" newline) are not supported, but "forced linebreaks" (<br>s) are allowed (signified by two spaces at the end of a line and then a newline). In other words, you have one kind of linebreak allowed in your stat blocks, but not the other kind.

The first question would be, if that's even a bug.

I don't know if you can selectively enable some features of markdown, I don't think markdownIt supports that. So the "fix" would be to enable all block elements, which would also enable horizontal lines, headings, lists and so on.

The second question would thus be: do you want to allow all block elements? You can of course do it, but most elements would probably break the styling of the stat block. This would need to be tested.
