### ISSUE TITLE
New Subscriber Not able to import from DND Beyond

### ISSUE THREAD

**Issue by ScullCleaver** [cynicaloptimist/improved-initiative#546]
Evan, I became a patron, installed the improved initiative extension within chrome.  Logged in to both DND Beyond and the Patreon several times. However when I go to use it I get in error.  I get the pop up to import to improved initiative.  It is populated with script.  I click the Import button and get from within the Improved Initiative Program "The D&D Beyond StatBlock Importer is available for Epic Initiative Patrons." The stat block does not then show within the library.

**Comment by cynicaloptimist** [comment]
Resolved through email. Generally this is resolved by logging out and back in.
