### ISSUE TITLE
Version 2.18.0 breaks the persistent counter feature

### ISSUE THREAD

**Issue by nmeier** [cynicaloptimist/improved-initiative#549]
the feature where you enter [1/3] into the persistent notes seems broken in rendering (tested https://improved-initiative-dev.herokuapp.com/e/)

2.18.0 

![image](https://user-images.githubusercontent.com/312857/123514769-83b8d680-d662-11eb-9cac-3380adb6f11f.png)

2.17.0
![image](https://user-images.githubusercontent.com/312857/123514776-8f0c0200-d662-11eb-8360-fe00bd2d7a2f.png)

**Comment by cynicaloptimist** [comment]
I reverted react-markdown to 4.0.3 to fix this. The TextEnricher class is ripe for a rewrite with updated libraries.
