### ISSUE TITLE
Version 2.18.0 loses character information post reload

### ISSUE THREAD

**Issue by nmeier** [cynicaloptimist/improved-initiative#550]
Start a new encounter, add sample characters

![image](https://user-images.githubusercontent.com/312857/123514835-d85c5180-d662-11eb-9378-46bfdfc4f05d.png)

Reload the browser window (Firefox here), notice that characters are 'empty'

![image](https://user-images.githubusercontent.com/312857/123514864-f7f37a00-d662-11eb-9e5f-d13b04466286.png)

**Comment by cynicaloptimist** [comment]
Thanks for the report, I need to hammer on Persistent Characters a bit more before this one's ready for primetime.
