### ISSUE TITLE
npm start doesn't work, no error message

### ISSUE THREAD

**Issue by cristianmtr** [cynicaloptimist/improved-initiative#558]
Hey. I installed everything, did `npx grunt`, and then at start it doesn't start:

```
npm run start

> improved-initiative@3.0.6 start /home/cristian/apps/improved-initiative-original
> node server/server.js

No connection string found, initializing in-memory DB
```

Nothing is using port 80. Also tried `sudo` and different port.

Ubuntu 20.04, node 12.9.1

**Comment by cynicaloptimist** [comment]
Might be failing to run the in-memory mongoDB server.

**Comment by cynicaloptimist** [comment]
You might have better luck now, I've made some of the dependency versions more explicit. Feel free to reopen if you have a repro with more detail.
