### ISSUE TITLE
Stat block layout seems pretty cramped

### ISSUE THREAD

**Issue by Azzurite** [cynicaloptimist/improved-initiative#57]
I can not objectively quantify this, but the stat block seems cramped and kind of unorganized. For example, a name like "skills" is imediately followed by the accompanying text. Maybe something like aligning the text on the right or adding a little bit of margin or line breaks could make the stat block look more readable.

I would be willing to work on this and provide a pull request some time in the future.

**Comment by cynicaloptimist** [comment]
Agreed- feel free to submit a PR, this would be very helpful.

**Comment by jimtahu** [comment]
@Azzurite if you want to get fancy, [statblock5e](https://github.com/Valloric/statblock5e) provides a very nice pretty print for stat blocks.

**Comment by cynicaloptimist** [comment]
@jimtahu do you know if the OGL allows for using wotc styles this way?

**Comment by jimtahu** [comment]
@cynicaloptimist I am afraid that I do not know one way or another. I also just noticed that the project I linked currently only works for Chrome.

**Comment by cynicaloptimist** [comment]
Yeah, that's a problem if it doesn't work in Chrome. Although I definitely agree that the styling of the statblocks could be improved, I do want to keep a distinctive style for Improved Initiative.

**Comment by Azzurite** [comment]
I will shortly start some work on this. Sorry for the delay, some other stuff had higher priority for me :D

**Comment by cynicaloptimist** [comment]
Thanks for the update- FYI, I'm currently reworking the whole site's CSS from the ground up with Bootstrap, so you might want to hold off.

**Comment by Azzurite** [comment]
Well, then, okay.

**Comment by cynicaloptimist** [comment]
Hi @Azzurite, I've merged in the changes- I didn't wind up doing updates quite as drastic as I'd expected. The CSS should be stable for the time being, so feel free to tweak the statblocks at your leisure.
