### ISSUE TITLE
The user poll queue is very small and easily overlooked

### ISSUE THREAD

**Issue by Azzurite** [cynicaloptimist/improved-initiative#58]
It happened multiple times for me that I clicked on something, the user poll queue at the bottom showed up and I didn't even notice it.

It should be made bigger and stand out a little more.

I would be willing to work on this and provide a pull request some time in the future.

**Comment by cynicaloptimist** [comment]
This is reasonable. I recently moved the poll div to the bottom of the window; it appeared immediately after the combatant list before. I'm open to suggestions on how to make the polls more visible while still looking relatively good.

**Comment by cynicaloptimist** [comment]
I slightly embiggened the poll window, and I made it do a little animation when you click 'Start Encounter' multiple times. Since this is probably the 99% case where people don't see it the first time.
