### ISSUE TITLE
A queue for "user polling" sometimes does not make sense from a UX standpoint

### ISSUE THREAD

**Issue by Azzurite** [cynicaloptimist/improved-initiative#59]
For example, you click two times (maybe by accident) on "set initiative" for a combatant. Or maybe you click on "set initiative", remember that you did not want that and click "rename combatant" instead.

In any case, you're left with dealing with the first dialog, even if you only wanted the last one.

I don't really think a queue makes sense for those kind of actions, when you click a button, as a user, you want to immediately perform the action that you clicked on, and not click on multiple actions to put them in a list and deal with them later.

The question is if there are valid usecases in the app for a user poll queue. Normally I would think of a UserPollQueue when the *application* is generating requests that have to be answered by the user. Is this the case for Improved Initiative? 

I personally have not found any instances of this (which doesn't mean much). As I see it, every usage of the UserPollQueue seems to be a direct response to the user clicking something. If that is true, my suggestion would be to remove the UserPollQueue and replace it with something more direct and blocking, like a modal popup.

Comments welcome.

**Comment by Azzurite** [comment]
#58 could be related to this/be worked on together, depending on what consensus is reached on this issue.

**Comment by cynicaloptimist** [comment]
I think you're making some good points here. My main (and maybe only) reason for the way UPQ is implemented now is due to a perhaps misguided goal of never blocking the UI with a modal dialog. However, as you note, since these are always in response to a user clicking a button, it may be OK to block the rest of the UI while a dialog is active. It's very easy to frustrate users by blocking the UI in a way they don't expect.

**Comment by cynicaloptimist** [comment]
Here's an article that helps to explain some of my reasons for avoiding modal behavior. https://developer.appway.com/screen/ShowSingleRecipe/selectedRecipeId/1390246496349

**Comment by cynicaloptimist** [comment]
I think there's a solid case for not completely blocking the UI. Consider a case where the user clicks a button, but wants to refer to a statblock before submitting their answer. They might want to reference a statblock from the library, or click on a combatant to view their statblock. I'm leaning toward doing the minimum to fix the situation you're describing with this issue- disable the 'Roll Initiative' button while there are initiative rolls pending, and disable other buttons only in very particular circumstances. I recently improved the logic around whether an encounter is Active or Inactive, and this state has some implications on whether start/stop encounter are valid commands.

**Comment by Azzurite** [comment]
The modal thing was a suggestion, I haven't thought about the points you listed here, and I agree with your assessment.

The main point of this issue was more that the "queue" part doesn't make sense. It would be fine if the current UserPollQueue Look-And-Feel stays, but it wouldn't be possible to have multiple dialogs.

 I don't really care about what replaces it, the modal thing was just a quick suggestion, I actually didn't put much thought in it :D You definitely have good points here and I agree with you, being able to see stuff while the dialog is open definitely makes sense.

I wouldn't see disabling buttons being part of this issue, though, I think that's more of a separate thing.

**Comment by cynicaloptimist** [comment]
This makes sense. In any case, your feedback helped me think over my reasons for building it the way I did, which is very helpful.

Currently, the only reason that UPQ is a *queue* is for the roll initiative case, in which I want to prompt the user to provide initiative rolls one at a time. This allows for a UI flow of typing a number, pressing 'enter', and repeating. I could provide all of the PC initiative prompts inline- most users are probably savvy enough to use the tab key to cycle between multiple fields when they're on the screen.

As you've noted, the current behavior means that interacting with the controls enqueues the relevant prompts behind the current prompt. A good change here might be to do away with the queue behavior altogether, and do something like visually flash the current poll (and ignore the command) when the user clicks a button that would create a new poll.
