### ISSUE TITLE
Adding combatant with random HP is bugged

### ISSUE THREAD

**Issue by Azengar** [cynicaloptimist/improved-initiative#594]
Hi,

Adding a combatant with random HP on the live version does not work properly.

When you add the first instance of a monster to the current encounter it always use the default HP, then the upcoming ones of the same type have random HPs.

**Comment by cynicaloptimist** [comment]
I think this is fixed, couldn't repro

**Comment by Azengar** [comment]
Hi, yes it was fixed at some point. don't know exactly when. Thanks!
