### ISSUE TITLE
"Download all synced data to local data" not working.

### ISSUE THREAD

**Issue by xcv142** [cynicaloptimist/improved-initiative#601]
[Same issue as this post from February.](https://www.patreon.com/posts/62950101)
Basically nothing happens when I press "Download all synced data to local data", the page refreshes, but that's it.

What have I tried: Logging out and in again. Deleting local data. Disable all my ad-blockers, vpn etc. Try it in Chrome, Firefox, Edge on Win 11, Ubuntu 20, and my Phone too. Increase Firefox's local storage quota to a whopping 100MB because I thought it might be related to [this older issue](https://github.com/cynicaloptimist/improved-initiative/issues/285); and my number of creatures is quite large (way less than 100MB though).

Not a webdev, so not too familiar with the console errors, but there are some that occur.

**Comment by cynicaloptimist** [comment]
I think this is fixed now as of a recent update. Feel free to re-open if you're still seeing it and I'll get in touch.
