### ISSUE TITLE
Prompts obscure the Settings pane

### ISSUE THREAD

**Issue by NielR** [cynicaloptimist/improved-initiative#628]
The prompts obscure the Settings pane when it is open. 
Easily fixed by setting z-index of ".prompts" to 1 (Settings has z-index 3, the blur modal has z-index 2, I noticed).

![2024-02-19--12-15-37__chrome_Combat_Tracker_-_Improved_Initiative_-_Google_Chro](https://github.com/cynicaloptimist/improved-initiative/assets/2423125/639a446b-6331-4785-8e65-188454cf175b)

**Comment by cynicaloptimist** [comment]
I think this is fixed.
