### ISSUE TITLE
Statblock editor redesign

### ISSUE THREAD

**Issue by cynicaloptimist** [cynicaloptimist/improved-initiative#67]

**Comment by cynicaloptimist** [comment]
Update: no longer horrifying. Still needs work.

**Comment by paulmoliva** [comment]
Where is the stat block editor accessed?

**Comment by cynicaloptimist** [comment]
The template is at improved-initiative/html/templates/editstatblock.html, and the css is in improved-initiative/lesscss/improved-initiative.less under .editor { }
