### ISSUE TITLE
Support advantage on initiative rolls

### ISSUE THREAD

**Issue by bloodearnest** [cynicaloptimist/improved-initiative#68]
Various things can give players advantage on initiative rolls, e.g. UA Ranger's Natural Explorer, or Sentinel Shield magic item.

Be great if we would flag *players* as having such a condition, and it be included in the initiative rolling.

Happy to look at adding this myself, but want to check it was something that was wanted by others.

Thanks.

**Comment by elinya** [comment]
I'd love to see it in II. I have 2/5 players with advantage on initiative. For now I simply add a flat +3. But that is not the same as advantage.
