### ISSUE TITLE
Rewind not rewinding timed notes

### ISSUE THREAD

**Issue by elinya** [cynicaloptimist/improved-initiative#74]
When rewinding a turn, the applied notes with an associated timer will not re-appear if the timer ended with the change of turn.
Example:
-Actors-
Player
Monster

Round 1
-Top of initiative -> Player Turn 1
Player1, poisons Monster until the end of their next turn. DM applies timed tag that will end after Monster Turn 1.
-Next turn -> Monster Turn 1
Monster is poisoned [and misses its attack due to disadvantage]
-Next turn -> Player Turn 2
DM realises that Monster has an ability to remove poison from self or friendly target.
-Previous turn -> Monster Turn 1
Monsters tag is not back.

**Comment by cynicaloptimist** [comment]
It would probably be reasonable to just hide timers with negative durations, instead of removing them altogether.
